### ISSUE TITLE
altRepGroup support

### ISSUE THREAD

**Issue by jbarth-ubhd** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#11]
For `<mods:accessCondition>` we're migrated to `altRepGroup="…"` to indicate the same thing in different languages. This could lead to »Widersprüchliche Rechteangaben in mods:accessCondition[@type=’use and reproduction’]« → `amdSec_16`. Is there support for `altRepGroup`?

**Comment by tschleier** [comment]
At the moment our validation doesn't support the attribute `altRegGroup` in any element as we have not processed any records using it in a way relevant for the DDB yet.

The test `amdSec_16` should only trigger if a record contains two different [valid URIs for right statements](https://pro.deutsche-digitale-bibliothek.de/daten-liefern/teilnahmekriterien/rechtliches/lizenzen-und-rechtehinweise-der-lizenzkorb-der-deutschen-digitalen-bibliothek) in `mods:accessCondition[@type='use and reproduction']` elements (element text or attribute `href`).\
Please give us an example record and we will look into it.

**Comment by jbarth-ubhd** [comment]
Here an example: https://digi.ub.uni-heidelberg.de/diglitData/mets/schliemann1884.xml 

![grafik](https://github.com/Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation/assets/30653779/b2d6553a-630a-4114-9433-9f50600aa832)

**Comment by tschleier** [comment]
We've discussed the `altRepGroup` attribute on our side but decided against supporting it.
The main reasons are, that it is hardly used in our context, can be used on many elements and the values are not controlled. This would complicate the DDB-METS/MODS Application Profile and our validations.

The example [schliemann1884.xml](https://digi.ub.uni-heidelberg.de/diglitData/mets/schliemann1884.xml) does not trigger `amdSec_16`. The rule removes the `deed...` part of the license URIs before comparing.

If you have another example that causes a false positive on `amdSec_16` we can look into it.
