### ISSUE TITLE
medien.sch titleInfo_02 too strict?

### ISSUE THREAD

**Issue by bertsky** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#13]
I believe the pattern for `titleInfo_02` in the Medien profile is overly strict: In https://github.com/Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation/blob/631fcdd6092fc1d0621501857ae3c1aac0afa96b/mets-mods-ap-digitalisierte-medien/ddb_validierung_mets-mods-ap-digitalisierte-medien.sch#L1218 **all** (non-primary) `dmdSec`s are required to have a title. 

But what about additional `dmdSec` for subunits without a proper title – like `dedication` in [this example](https://digital.slub-dresden.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-273657100) under `@DMDID="uuid-76157dfe-172d-3087-9203-6ae6809c2cb5"`?

Or what about additional `dmdSec` which just concern physical information (like paper format) and point to the `PHYSICAL` rather than the `LOGICAL` structMap – like in [this example](https://digital.slub-dresden.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-1662983913) – or is it invalid to have dmdSecs for physical divs?

In comparison, the DFG MODS application profile (version 2.3.1, section 2.1 on titles) only states that titles are required for the root (primary) unit of a work – but (explicitly) not for dependent parts of a work like volumes or issues, which can be derived from the `mods:relatedItem` or the title of the parent mptr, and (by extension) not for subunits like chapters and sections, which can be derived from the `mets:div/@LABEL`.

IIUC the DDB MODS application profile is more strict here, esp. for [dependent parts](https://wiki.deutsche-digitale-bibliothek.de/pages/viewpage.action?pageId=78512646#id-2.3.METS/MODSf%C3%BCrUnselbst%C3%A4ndigeDokumente-BeschreibunginMODS). 

So I wonder:
1. why the discrepancy with DFG regarding dependent parts and subunits?
2. shouldn't metadata about a physical unit still be unconstrained?

**Comment by tschleier** [comment]
Yes, the DDB MODS application profile is stricter here and the `titleInfo_02` validation enforces an additional requirement for the DDB.
The reason for this is that during ingest, each `mets:dmdSec` element in a mets record creates an object in the DDB. Objects require a title, so no additional information can be displayed without one.

Technically, `mets:dmdSec` elements without titles are removed during the ingest process and their information is lost and not displayed in the DDB. The linked `mets:div` in `mets:structMap[@TYPE='LOGICAL']` will still be displayed under "Related objects" (e.g. [this record](https://www.deutsche-digitale-bibliothek.de/item/BBILES7IOKW5YOZD63XP5NY6UXQCALFL), at the bottom) if it contains at least one `mets:div` element with a "valid" linked `mets:dmdSec`.

**Comment by bertsky** [comment]
Ok, thanks for the explanation!

But then why do I still see the dedication section (even with a translation `Widmung`) in the [DDB book viewer for my example](https://www.deutsche-digitale-bibliothek.de/item/QEJ6DUKOHYEECWQAUKERVDMQPO2LU7FW?isThumbnailFiltered=true&query=http%3A%2F%2Fdigital.slub-dresden.de%2Fid273657100&rows=20&offset=0&viewType=list&hitNumber=1)?

**Comment by sebastian-meyer** [comment]
> But then why do I still see the dedication section (even with a translation `Widmung`) in the [DDB book viewer for my example](https://www.deutsche-digitale-bibliothek.de/item/QEJ6DUKOHYEECWQAUKERVDMQPO2LU7FW?isThumbnailFiltered=true&query=http%3A%2F%2Fdigital.slub-dresden.de%2Fid273657100&rows=20&offset=0&viewType=list&hitNumber=1)?

That's because the DDB book viewer actually uses the DFG Viewer technology. Thus it doesn't rely on the ingested/processed metadata, but directly consumes the original METS files and applies the standard DFG Viewer application profiles.

**Comment by bertsky** [comment]
@sebastian-meyer thanks – that makes sense!

So to summarise:
1. `titleInfo_02` enforces a particular DDB convention which only affects whether dependent parts and subunits of a work can be referenced **as objects** in the DDB portal, but not whether they can be seen in the document structure of the DDB book viewer of the parent object (or other DFG Viewer-based presentation systems); DDB ingest of the parent object is unaffected
2. therefore, the error can be ignored entirely for MODS entries pointing to physical structure.

Again, many thanks for clarifying!
