### ISSUE TITLE
Inconsistency of accepted logical struct types

### ISSUE THREAD

**Issue by M3ssman** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#14]
# Description

Since latest release, DDB-Validation increased it's ruleset with `structMapLogical_27` . 

This breaks internal workflow stuff of [ULB Sachsen-Anhalt](https://bibliothek.uni-halle.de/) when using DDB-Validation, since it doesn't like all types from [DFG-Viewer set](https://dfg-viewer.de/strukturdatenset). At least `cover_front` and `cover_back` are missing, which are included in virtually in all our digital objects, actually a total of more than 80.000 retro prints, including several thousands volumes.

Unfortunately, I don't get the rationale behind `strucMapLogical_27`. Rule `strucMapLogical_06` already does a very similar thing for any object type, not only for `unselbstständige Dokument` types and in a more rigid way, alerting an `error` if it finds unexpected structs. Even worse, `strucMapLogical_27` interferes with `strucMapLogical_06` because there are more sub types included like `cover_front` and `cover_back`.

**Comment by tschleier** [comment]
Yes, the tests are similar, but they validate against different "vocabularies":

* `structMapLogical_06` validates against the [Structural data set of the DFG-Viewer](https://dfg-viewer.de/strukturdatenset).
* `structMapLogical_27` validates against the [DDB Hierarchietyp vocabulary](http://ddb.vocnet.org/hierarchietyp/), which contains fewer terms but with definitions.

The terms in the Structural data set of the DFG-Viewer are used as keys for multilingual labels in the DFG-Viewer. They lack definitions, have increased in count over the years, and are used somewhat freely. To address this, we created the test `structMapLogical_27` (along with `structMapLogical_25` and `structMapLogical_26`) as a first step towards introducing semantics to the structtype for the DDB.

This will eventually enable us to better validate records for the DDB and enhance the search experience for our users.

These tests are currently just warnings, so you can ignore them for now. Additionally, we plan to reference the DDB Hierarchietyp vocabulary on the DFG-Viewer website in the future.

We understand that adjusting structtypes is a significant change and so we are slowly approaching this topic.

**Comment by M3ssman** [comment]
Thanks for your explanations! To reflect this, I've recently added the ability to filter DDB-Meldungen by level (according to their plain ID, which was the way we did it before). Please take a look at [metadata_ddb python module](https://github.com/ulb-sachsen-anhalt/digital-flow/blob/main/src/digiflow/validate/metadata_ddb.py) to get an idea how we prepare metadata to get closer to what the DDB propagates.
