### ISSUE TITLE
Changed behavior for note_01

### ISSUE THREAD

**Issue by M3ssman** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#3]
# Description

In between 2022-02 -24 and 2022-04-07 schematron-validation `ddb_validierung_mets-mods-ap-digitalisierte-medien.sch` changed the way to validate `mods:note`. 

Formerly, a subtree of 

```
          <mods:location>
            <mods:holdingSimple>
              <mods:copyInformation>
                <mods:shelfLocator>Pon Yb 291, 4° (2. Ex.)</mods:shelfLocator>
                <mods:note>digitized copy</mods:note>
              </mods:copyInformation>
            </mods:holdingSimple>
          </mods:location>
```

resulted into `note_01`errors, because of the note missing attribute type, which is not the case with the recent version.

The change both affects `note_01` and `note_02`, but I don't have a test-case for `note_02` at hand.

Is this *really* desired behavior?

**Comment by M3ssman** [comment]
Regarding the change log entry from 2022-04-01, in my interpretation, the aim was to precise the xPath expression, not to change behavior.

**Comment by tschleier** [comment]
Yes, the DDB only supports `mods:note`  as top level element or as child of `mods:physicalDescription` (we don't process other `mods:note`).  So limiting `note_01` and `note_02` to `[ancestor::mods:mods]` was unprecise.

 `mods:copyInformation` is hardly used in the records we get so we just recently noticed this problem.
