### ISSUE TITLE
Inconsistency between Validation for Zeitungen and Medien

### ISSUE THREAD

**Issue by M3ssman** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#9]
# Description

In the validation-schemas for type `zeitungen` the MIME-Type of OCR-Data is checked as `text/xml` , whereas for `medien`  there is no such a requirement - there are no constraints for OCR integrated. What's the reason for this?

**Comment by tschleier** [comment]
The validation-schema for the `medien` application profile is used for METS-records for the general DDB Portal, which does not support OCR-Data at the moment. For this reason, the validation-schema ignores ORC-Data.

The Zeitungsportal does support (and encourages the use of) OCR-Data and requires the specific MIME-type.
